---
- name: Create Role Binding
  kubernetes.core.k8s:
    namespace: "{{ magma_namespace }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: prometheus-cache-cleanup-role-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: prometheus-cache-cleanup-role
      subjects:
        - kind: ServiceAccount
          name: "{{ prometheus_service_account_name }}"
