---
- name: Create Service Account
  kubernetes.core.k8s:
    namespace: "{{ magma_namespace }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ prometheus_service_account_name }}"
